# Generated by Django 5.2.16 on 2026-07-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paldeck_id', models.PositiveIntegerField()),
                ('key', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.CharField(blank=True, max_length=200)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('suitability', models.JSONField(blank=True, default=list)),
                ('drops', models.JSONField(blank=True, default=list)),
                ('breeding_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('raridade', models.PositiveIntegerField(blank=True, null=True)),
                ('genus', models.CharField(blank=True, max_length=50)),
                ('descoberto', models.BooleanField(default=False)),
                ('descoberto_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipos', models.ManyToManyField(blank=True, to='paldeck.tipo')),
            ],
            options={
                'verbose_name_plural': 'pals',
                'ordering': ['paldeck_id', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Breeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nasce_de', to='paldeck.pal')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='paldeck.pal')),
                ('pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='paldeck.pal')),
            ],
            options={
                'verbose_name': 'breeding',
                'verbose_name_plural': 'breedings',
                'constraints': [models.UniqueConstraint(fields=('filho', 'pai', 'mae'), name='breeding_unico')],
            },
        ),
    ]
