# Generated by Django 5.2.16 on 2026-07-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paldeck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pal',
            name='breeding_rank',
        ),
        migrations.RemoveField(
            model_name='pal',
            name='skills',
        ),
        migrations.AddField(
            model_name='pal',
            name='equipamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pal',
            name='noturno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pal',
            name='passiva',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pal',
            name='passiva_descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pal',
            name='preco_venda',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pal',
            name='tamanho',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pal',
            name='taxa_fome',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
